# Generated by Django 3.0.8 on 2021-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
