# Generated by Django 3.0.8 on 2021-03-16 14:40

import AdminApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_to', models.CharField(max_length=255)),
                ('donated_amount', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasteType', models.CharField(choices=[('Food', 'Food'), ('Cloth', 'Cloth')], default='Food', max_length=10)),
                ('statusType', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('Pickedup', 'Pickedup'), ('assignteam', 'assignteam'), ('donated', 'donated')], default='pending', max_length=10)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('DOB', models.DateField()),
                ('address', models.TextField()),
                ('contact_No', models.IntegerField()),
                ('userType', models.CharField(choices=[('Doner', 'Doner'), ('staff', 'staff')], default='Doner', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PickedUp', 'PickedUp'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='PickedUp', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.Donate')),
                ('wastage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.Wastage')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.BigIntegerField(default=AdminApp.models.Track.TrackingIdGen)),
                ('shipped_by', models.CharField(max_length=255)),
                ('delivery_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(max_length=255)),
                ('delivery_by_phn_no', models.PositiveIntegerField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Picked by courier', 'Picked by courier'), ('On the way', 'On the way'), ('Ready for pickup', 'Ready for pickup'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Wastage')),
            ],
        ),
        migrations.CreateModel(
            name='PickupTeamUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_boy_id', models.BigIntegerField(default=AdminApp.models.PickupTeamUserProfile.idgen)),
                ('name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('address', models.TextField()),
                ('contact_No', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('Doner', 'Doner'), ('staff', 'staff')], default='Doner', max_length=10)),
                ('Type', models.CharField(choices=[('a', 'a'), ('b', 'b')], default='a', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wastage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Wastage')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.SmallIntegerField(default=AdminApp.models.OTP.otpgen)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='wastage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.Wastage'),
        ),
        migrations.CreateModel(
            name='distributionteamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_boy_id', models.BigIntegerField(default=AdminApp.models.distributionteamProfile.idgen)),
                ('name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('address', models.TextField()),
                ('contact_No', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('Doner', 'Doner'), ('staff', 'staff')], default='Doner', max_length=10)),
                ('Type', models.CharField(choices=[('a', 'a'), ('b', 'b')], default='a', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wastage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Wastage')),
            ],
        ),
    ]
