# Generated by Django 3.0.7 on 2021-05-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastage',
            name='pic2',
        ),
    ]
