from django.contrib import admin
from django.urls import path
from AdminApp.views import Auth_Register_View,index_view,Auth_Login_View,editdistributionteam,deletedistributionteam,confirmdistributionview,ChangePhotoAdmin,UserProfileAdmin,confirmdistrib,confirmpickup,confirmview,assigndistribution,deletepickupboy,editpickupboy,Assignpickupteam,showpickteam,distributionteam,addstockview,deletestock,pickupview,editpickup,deletedistribution,editdistribution,deletepickup,adddistributionteam,stockupdateview,distributionteamview,pickupteamprofile,edituser,Allusers,UserDetails,addpickupboy, trackwasteview,CreateTrack,TrackingId,track_view,donatehistory,Login,Logout,OTPverify,CollectFood,CollectCloth,ChangePassword,ForgotPassword,UserProfileUser,Rejectwaste,userapproval,ChangePhotoUser,indexadminview
from PublicApp.views import public_index_view,public_about_view,public_contact_view,public_service_view,public_feedback_view
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',Login,name='login'),
    path('otpverify/',OTPverify,name='otpverify'),
    path('logout/',Logout,name='logout'),
    path('register/',Auth_Register_View,name='register'),
    path('admin-login/',Auth_Login_View,name='admin-login'),
    path('admin-index/',index_view,name='admin-index'),
    path('',public_index_view,name='public-index'),
    path('public-about/',public_about_view,name='public-about'),
    path('public-contact/',public_contact_view,name='public-contact'),
    path('public-service/',public_service_view,name='public-service'),
    path('public-feedback/',public_feedback_view,name='public-feedback'),
    path('confirm/',confirmview,name='confirm'),
    path('confirm1/',confirmdistributionview,name='confirm1'),
    path('trackingid/<int:id>/',TrackingId, name="trackingid"),
    path('assignpickup/<int:id>/',Assignpickupteam),
    path('confirmpickup/<int:id>/',confirmpickup),
    path('confirmdistrib/<int:id>/',confirmdistrib),
    path('assignd/<int:id>/',distributionteam),
    path('showpickteam/',showpickteam,name='showpickteam'),
    path('assigndistribteam/',assigndistribution,name='assigndistribteam'),
    path('editpickupboy/<int:id>/',editpickupboy),
    path('deletepickupboy/<int:id>/',deletepickupboy),
    path('editdistributionteam/<int:id>/',editdistributionteam),
    path('deletedistributionteam/<int:id>/',deletedistributionteam),
    path('create-track/<int:id>/',CreateTrack, name="create-track"),
    path('collect-food/',CollectFood,name='collect-food'),
    path('collect-cloth/',CollectCloth,name='collect-cloth'),
    path('changepassworduser/', ChangePassword, name="changepassworduser"),
    path('forgotpassword/', ForgotPassword, name="forgotpassword"),
    path('userprofile/',UserProfileUser,name='userprofile'),
    path('userprofileadmin/',UserProfileAdmin,name='userprofileadmin'),
    path('changephotouser/',ChangePhotoUser,name='changephoto'),
    path('changephotoadmin/',ChangePhotoAdmin,name='changephoto'),
    path('indexadmin/',indexadminview,name='indexadmin'),
    path('userapproval/',userapproval,name='userapproval'),
    path('rejectwaste/<int:id>',Rejectwaste),
    path('donatehistory/',donatehistory,name='donatehistory'),
    path('track/',track_view,name='track'),
    path('pickup/',pickupview,name='pickup'),
    path('pickupteamprofile/',pickupteamprofile,name='pickupteamprofile'),
    path('addpickupboy/',addpickupboy,name='addpickupboy'),
    path('alluser/',Allusers,name='alluser'),
    path('userdetails/<int:id>/',UserDetails,name='userdetails'),
    path('edituser/<int:id>/',edituser,name='edit'),
    path('editpickup/<int:id>/',editpickup,name='edit1'),
    path('editdistribution/<int:id>/',editdistribution),
    path('deletepickup/<int:id>/',deletepickup),
    path('deletedistribution/<int:id>/',deletedistribution),
    path('trackwaste/',trackwasteview,name='trackwaste'),
    path('distributionteam/',distributionteamview,name='distributionteam'),
    path('adddistributionteam/',adddistributionteam,name='adddistributionteam'),
    path('stockupdate/',stockupdateview,name='stockupdate'),
    path('addstock/',addstockview,name='addstock'),
    path('deletestock/<int:id>/',deletestock),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
